In [7]:
import sklearn

In [14]:
#Example: 1/4 from http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html
#Includes my comments from video

import numpy as np

X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])

from sklearn.naive_bayes import GaussianNB

#Creating classifier
clf = GaussianNB()

#Training. X = features, Y = labels
clf.fit(X, Y)

GaussianNB(priors=None)

In [15]:
#Example: 2/4

print(clf.predict([[-0.8, -1]]))

[1]


In [16]:
#Example: 3/4

clf_pf = GaussianNB()
clf_pf.partial_fit(X, Y, np.unique(Y))

GaussianNB(priors=None)

In [17]:
#Example: 4/4

print(clf_pf.predict([[-0.8, -1]]))

[1]


#### Example code from sklearn documentation about SVMs



In [18]:
from sklearn import svm
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

After being fitted, the model can then be used to predict new values:

In [20]:
clf.predict([[2., 2.]])

array([1])

SVMs decision function depends on some subset of the training data, called the support vectors. Some properties of these support vectors can be found in members support_vectors_, support_ and n_support: 

In [21]:
# get support vectors
clf.support_vectors_

array([[ 0.,  0.],
       [ 1.,  1.]])

In [22]:
# get indices of support vectors
clf.support_ 

array([0, 1], dtype=int32)

In [23]:
# get number of support vectors for each class
clf.n_support_

array([1, 1], dtype=int32)

In [24]:
#Practice for lesson 3, vid 15

X = [[0, 0], [1, 1], [2, 2], [3, 3], [4,4]]
#y = [0, 1]
#Y = 

### Lesson 3: Decision Trees

In [28]:
from sklearn import tree
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [29]:
clf.predict([[2., 2.]])

array([1])

In [30]:
clf.predict_proba([[2., 2.]])

array([[ 0.,  1.]])

In [31]:
# Using the Iris dataset, we can construct a tree as follows:

from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()
clf = tree.DecisionTreeClassifier()
clf = clf.fit(iris.data, iris.target)

In [33]:
import graphviz 
dot_data = tree.export_graphviz(clf, out_file=None) 
graph = graphviz.Source(dot_data) 
graph.render("iris")

ModuleNotFoundError: No module named 'graphviz'

In [ ]:
dot_data = tree.export_graphviz(clf, out_file=None, 

graph = graphviz.Source(dot_data)  
graph 

In [ ]:
# After being fitted, the model can then be used to predict the class of samples:

clf.predict(iris.data[:1, :])
array([0])

In [ ]:
# Alternatively, the probability of each class can be predicted, which is the fraction of training samples of the same class in a leaf:

clf.predict_proba(iris.data[:1, :])
array([[ 1.,  0.,  0.]])

### Lesson 7: Regressions

#### Example code from sklearn documentation about Linear Models


In [1]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit ([[0, 0], [1, 1], [2, 2]], [0, 1, 2])

reg.coef_

array([ 0.5,  0.5])

### Lesson 10: Feature Scaling

##### Vid 10 quiz: Min/Max Rescaler

In [5]:
""" quiz materials for feature scaling clustering """

### FYI, the most straightforward implementation might 
### throw a divide-by-zero error, if the min and max
### values are the same
### but think about this for a second--that means that every
### data point has the same value for that feature!  
### why would you rescale it?  Or even use it at all?
def featureScaling(arr):
    
    x_min = min(arr)
    x_max = max(arr)
    
    max_minus_min = x_max - x_min
    
    new_array = list()
    
    for X in arr:
        val = (X - x_min) / (max_minus_min)
        new_array.append(val)
    
    return new_array

# tests of your feature scaler--line below is input data
data = [115, 140, 175]
print(featureScaling(data))


[0.0, 0.4166666666666667, 1.0]


#### Lesson 11: Text Learning

##### Vid 9 quiz: Getting stopwords from NLTK

In [6]:
from nltk.corpus import stopwords

In [10]:
sw = stopwords.words('english')

In [11]:
sw[3]

'myself'

In [12]:
len(sw)

179

#### Lesson 15: Evaluation Matrix

##### Vid 34 quiz: How many true positives?

In [2]:
predictions = [0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1] 
true_labels = [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0]

In [16]:
count = 0
for i in range(0,len(predictions)):
    if predictions[i] == 1 and true_labels[i] == 1:
        count += 1
        
count

6

##### Vid 35 quiz: How many true negatives?

In [10]:
count = 0
for i in range(0,len(predictions)):
    if predictions[i] == 0 and true_labels[i] == 0:
        count += 1
        
count

9

##### Vid 36 quiz: How many false positives?

In [11]:
count = 0
for i in range(0,len(predictions)):
    if predictions[i] == 1 and true_labels[i] == 0:
        count += 1
        
count

3

##### Vid 37 quiz: How many false negatives?

In [12]:
count = 0
for i in range(0,len(predictions)):
    if predictions[i] == 0 and true_labels[i] == 1:
        count += 1
        
count

2

##### Vid 38 quiz: Precision

In [14]:
from sklearn.metrics import precision_score

In [15]:
precision_score(true_labels, predictions)

0.66666666666666663

##### Vid 39 quiz: Recall

In [18]:
from sklearn.metrics import recall_score

In [19]:
recall_score(true_labels, predictions)

0.75