In [1]:
#function to print 5 rows
def five_rows(table):
    count = 0
    
    if type(table) == dict:
        for row in table:
            count += 1 
            print(row,table[row])
            if count == 5:
                break
    else:
        for row in table:
            count += 1 
            print(row)
            if count == 5:
                break
                
def print_line(dot=False):
    if dot == True:
        print('---------------------------')
    else:
        print('___________________________')

In [4]:
#Quiz: Subway data: taking a look at the data
import pandas as pd

subway_weather = pd.read_csv('nyc_subway_weather.csv')

five_rows(subway_weather)

UNIT
DATEn
TIMEn
ENTRIESn
EXITSn


In [6]:
subway_weather[1:5]

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week     ...       pressurei  \
1            0.0  2011-05-01 04:00:00     4         6     ...           30.25   
2            0.0  2011-05-01 12:00:00    12         6     ...           30.28   
3            0.0  2011-05-01 16:00:00    16         6     ...           30.26   
4            0.0  2011-05-01 20:00:00    20         6     ...           30.28   

  rain  tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  \
1    0   52.0    3.5         0.0         30.258      55.98       7.86   
2    0   62.1    6.9         0.0         30.258      55.98       7.86   
3    0   57.9   15.0         0.0         30.258      55.98       7.86   
4    0   52.0   10.4         0.0         30.258      55.98       7.86   

   weather_lat  weather_lon  
1    40.700348   -73.887177  
2    40.700348   -73.887177  
3    40.700348   -73.887177  
4    40.700348   -73.887177  

[4 rows x 27 columns]

**Quiz: Subway data, my questions**

1. How much does precipitation affect ridership?
2. How does temperature affect ridership?
3. Is there a threshold for temperature and/or precipitation where ridership is drastically increased?
4. When adjusting for other variables, does wind still affect ridership?
5. Are the results for the questions above consistent across all stations?

**Quiz: Subway data, instructor's questions**
1. What variables are related to subway ridership?
    a. Which stations have the most riders?
    b. What are the ridership patterns over time?
    c. How does the weather affect ridership?
2. What patterns can I find in the weather?
    a. Is the temperature rising throughout the month (May)?
    b. How does weather vary across the city?

**Two-dimensional data**

- Rows and columns
- Python: list of lists
- NumPy: 2D array
    - 2D arrays, as opposed to arrays of arrays:
        - More memory efficient
        - Accessing elements is a bit different
            - 2D array: a[1,3]  array of arrays: a[1][3]
                - row 1, column 3
                - can also use slice, e.g. a[1:4,3:5]
                - mean(), std(), etc. operate on entire array
- Pandas: DataFrame

In [15]:
#Two-Dimensional NumPy Arrays, example code
import numpy as np

# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

# Change False to True for each block of code to see what it does

# Accessing elements
if False:
    print(ridership[1, 3])
    print(ridership[1:3, 3:5])
    print(ridership[1, :])
    
# Vectorized operations on rows or columns
if False:
    print(ridership[0, :] + ridership[1, :])
    print(ridership[:, 0] + ridership[:, 1])
    
# Vectorized operations on entire arrays
if False:
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
    print(a + b)



[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [25]:
#Quiz: Two-Dimensional NumPy Arrays

def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    overall_mean = ridership.mean() # Replace this with your code
    mean_for_max = ridership[:,np.argmax(ridership[0])].mean() # Replace this with your code
    
    return (overall_mean, mean_for_max)

In [26]:
mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)

In [29]:
#Quiz: Two-Dimensional NumPy Arrays, instructor's solution

def mean_riders_for_max_station(ridership):

    max_station = ridership[0, :].argmax()
    
    overall_mean = ridership.mean() # Replace this with your code
    mean_for_max = ridership[:, max_station].mean() # Replace this with your code
    
    return (overall_mean, mean_for_max)

Operations along an axis

- Most functions built into numpy takes an axis argument
    - column: axis=0
    - row: axis=1

In [32]:
#Numpy Axis, example code

import numpy as np

# Change False to True for this block of code to see what it does

# NumPy axis argument
if False:
    a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
    
    print(a.sum())
    print(a.sum(axis=0))
    print(a.sum(axis=1))
    


[ 6 15 24]


In [35]:
#Quiz: NumPy Axis
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    
    mean_ridership_per_station = ridership.mean(axis=0)
    
    max_daily_ridership = mean_ridership_per_station.max()     # Replace this with your code
    min_daily_ridership = mean_ridership_per_station.min()     # Replace this with your code
    
    return (max_daily_ridership, min_daily_ridership)

In [36]:
min_and_max_riders_per_day(ridership)

(3239.9000000000001, 1071.2)

Instructor has same exact solution.

**Numpy and Pandas Data Types**

- NumPy 
    - each element in the array is expected to have the same array
        - including 2D arrays
            - makes it inconvenient to import CSVs
- Pandas
    - DataFrame
        - 2D data structure
        - each column is assumed to be a different type
        - have indexes, like pandas series.
            - Index=rows, name=columns

In [41]:
#Pandas Data Types example

enrollments_df = pd.DataFrame({
        'account_key': [448,448,448,448,448],
        'status': ['canceled','canceled','canceled','canceled','current'],
        'join_date:': ['2014-11-10','2014-11-05','2015-01-27','2014-11-10','2014-11-10'],
        'days_to_cancel': [65,5,0,0,np.nan],
        'is_udacity': [True,True,True,True,True]
    })

enrollments_df

account_key  days_to_cancel is_udacity  join_date:    status
0          448            65.0       True  2014-11-10  canceled
1          448             5.0       True  2014-11-05  canceled
2          448             0.0       True  2015-01-27  canceled
3          448             0.0       True  2014-11-10  canceled
4          448             NaN       True  2014-11-10   current

In [42]:
#Pandas Data Types example

enrollments_df.mean()
#Takes the mean of the numeric columns and ignores the others. 
#With 2D numpy arrays, this would fail, as not all columns are numeric.

account_key       448.0
days_to_cancel     17.5
is_udacity          1.0
dtype: float64

**Accessing elements of a DataFrame**

- Accessing a single row of a DataFrame is similar to accessing a single row of a Series
    - `ridership_df.loc['05-02-11'] #05-02-11 is index entry (row)`
- Single rows can also be accessed by position, using iloc
    - `ridership_df.iloc[9] #returns row 9 (row 10, since starts at 0)`
- To access a single element (single cell) can also be accessed using loc or iloc
    - `ridership_df.loc['05-02-11', 'R004'] #05-02-11 is index entry, R004 is name (column header)`
    - `ridership_df.loc[0, 3] #0 is row, 3 is column`
- Columns can be accessed using square brackets []
    - `ridership_df['R006']`
- To return only values (as numpy array?):
    - `ridership_df.values`
    - example use case: if you want to find the mean of all columns
        - `ridership_df.values.mean()`
        - be careful of data types if doing this
 

In [52]:
#Accessing elements of a DataFrame, code example

# Subway ridership for 5 stations on 10 different days
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

# Change False to True for each block of code to see what it does

# DataFrame creation
if False:
    # You can create a DataFrame out of a dictionary mapping column names to values
    df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
    print(df_1)

    # You can also use a list of lists or a 2D NumPy array
    df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
    print(df_2)
   

# Accessing elements
if False:
    print(ridership_df.iloc[0])
    print(ridership_df.loc['05-05-11'])
    print(ridership_df['R003'])
    print(ridership_df.iloc[1, 3])
    
# Accessing multiple rows
if False:
    print(ridership_df.iloc[1:4])
    
# Accessing multiple columns
if False:
    print(ridership_df[['R003', 'R005']])
    
# Pandas axis
if False:
    df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
    print(df.sum())
    print(df.sum(axis=1))
    print(df.values.sum())
    

15


In [57]:
ridership_df.iloc[0].argmax()

'R006'

In [61]:
#Quiz: Accessing elements of a DataFrame
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    max_Station = ridership.iloc[0].argmax()
    
    overall_mean = ridership.values.mean() # Replace this with your code
    mean_for_max = ridership[max_Station].mean() # Replace this with your code
    
    return (overall_mean, mean_for_max)

mean_riders_for_max_station(ridership_df)

(2342.5999999999999, 3239.9)

**Loading data into a Dataframe** 

 df.readcsv()

- Useful functions for viewing data:
    - `subway_df.head() #first rows`

In [118]:
#Quiz: calculating Correlation (Pearson's r)
'''
1. Start by standarizing:
    - convert to standard deviations below/above mean
2. Multiply each pair of values, and take the average
r = (average of x in std units) * (average of y in std units)
    - Ranges from -1 to +1
    - if positive value, both x and y increases or decreases
    - if negative value, one of x or y decreases as the other increases
    - Pearson's r only measures linear correlation! 

df.std()
- pass argument ddof=0 to ensure Bessel's correction is not used (used by default)

Pearson's r in NumPy
- NumPy's corrcoef() function can be used to calculate Pearson's r, also known as the correlation coefficient.


'''
filename = 'nyc_subway_weather.csv'
subway_df = pd.read_csv(filename)

def correlation(x, y):
    '''
    Fill in this function to compute the correlation between the two
    input variables. Each input is either a NumPy array or a Pandas
    Series.
    
    correlation = average of (x in standard units) times (y in standard units)
    
    Remember to pass the argument "ddof=0" to the Pandas std() function!
    '''
    x_std = (x - x.mean()) / x.std(ddof=0)
    y_std = (y - y.mean()) / y.std(ddof=0)
    
    return (x_std * y_std).mean()

entries = subway_df['ENTRIESn_hourly']
cum_entries = subway_df['ENTRIESn']
rain = subway_df['meanprecipi']
temp = subway_df['meantempi']

print(correlation(entries, rain))
print(correlation(entries, temp))
print(correlation(rain, temp))

print(correlation(entries, cum_entries))



0.03564851577223041
-0.026693348321569912
-0.22903432340833663
0.5858954707662182


I struggled with this one. In the end I had to view parts of the answer video to get on track.

My mistake was that I had used 
~~~~
return x_std.mean() * y_std.mean()
~~~~
instead of the correct answer
~~~~
return (x_std * y_std).mean()
~~~~